spring:
    datasource:
        url: ${DB_URL:jdbc:h2:mem:mydb}
        username: ${DB_USERNAME:username}
        password: ${DB_PASSWORD:password}
        driverClassName: org.h2.Driver
    jpa:
        spring.jpa.database-platform: org.hibernate.dialect.H2Dialect